/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtikelIdRouteImport } from './routes/artikel.$id'

const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIdRoute = ArtikelIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArtikelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/galeri': typeof GaleriRoute
  '/artikel/$id': typeof ArtikelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/galeri': typeof GaleriRoute
  '/artikel/$id': typeof ArtikelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/galeri': typeof GaleriRoute
  '/artikel/$id': typeof ArtikelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/artikel' | '/galeri' | '/artikel/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/artikel' | '/galeri' | '/artikel/$id'
  id: '__root__' | '/' | '/admin' | '/artikel' | '/galeri' | '/artikel/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArtikelRoute: typeof ArtikelRouteWithChildren
  GaleriRoute: typeof GaleriRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$id': {
      id: '/artikel/$id'
      path: '/$id'
      fullPath: '/artikel/$id'
      preLoaderRoute: typeof ArtikelIdRouteImport
      parentRoute: typeof ArtikelRoute
    }
  }
}

interface ArtikelRouteChildren {
  ArtikelIdRoute: typeof ArtikelIdRoute
}

const ArtikelRouteChildren: ArtikelRouteChildren = {
  ArtikelIdRoute: ArtikelIdRoute,
}

const ArtikelRouteWithChildren =
  ArtikelRoute._addFileChildren(ArtikelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArtikelRoute: ArtikelRouteWithChildren,
  GaleriRoute: GaleriRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
